### ISSUE TITLE
Installing in Apigility throws error

### ISSUE THREAD

**Issue by adamturcsan** [doctrine/DoctrineMongoODMModule#187]
Cannot make it work with a fresh apigility install. It always throws the following error. Composer can't finish its installation so it brakes all the system: it is put into modules.config.php but cannot load because it is not put into composer/installed.json and has no autoload config.

```
Installing DoctrineMongoODMModule from package doctrine/doctrine-mongo-odm-module
PHP Fatal error:  Uncaught Error: Class 'Doctrine\Common\Proxy\AbstractProxyFactory' not found in /home/junior/Munka/Utils/apigility/vendor/doctrine/doctrine-mongo-odm-module/config/module.config.php:26
Stack trace:
#0 /home/junior/Munka/Utils/apigility/vendor/zfcampus/zf-asset-manager/src/AssetInstaller.php(74): include()
#1 /usr/share/php/Composer/Plugin/PluginManager.php(178) : eval()'d code(65): ZF\AssetManager\AssetInstaller->__invoke(Object(Composer\Script\PackageEvent))
#2 [internal function]: ZF\AssetManager\Plugin_composer_tmp1->onPostPackageInstall(Object(Composer\Script\PackageEvent))
#3 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Script\PackageEvent))
#4 /usr/share/php/Composer/EventDispatcher/EventDispatcher.php(114): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\PackageEvent))
#5 /usr/share/php/Composer/Installer.php(590): Composer\EventDispatcher\EventDispatcher->dispatchPackageEvent('post-package-in...', true, Object(Compo in /home/junior/Munka/Utils/apigility/vendor/doctrine/doctrine-mongo-odm-module/config/module.config.php on line 26

Fatal error: Uncaught Error: Class 'Doctrine\Common\Proxy\AbstractProxyFactory' not found in /home/junior/Munka/Utils/apigility/vendor/doctrine/doctrine-mongo-odm-module/config/module.config.php on line 26

Error: Class 'Doctrine\Common\Proxy\AbstractProxyFactory' not found in /home/junior/Munka/Utils/apigility/vendor/doctrine/doctrine-mongo-odm-module/config/module.config.php on line 26

Call Stack:
    0.0002     359912   1. {main}() /usr/bin/composer:0
    0.0469     941728   2. Composer\Console\Application->run() /usr/bin/composer:44
    0.0510    1021792   3. Composer\Console\Application->run() /usr/share/php/Composer/Console/Application.php:99
    0.0529    1026792   4. Composer\Console\Application->doRun() /usr/share/php/Symfony/Component/Console/Application.php:120
    0.0559    1062696   5. Composer\Console\Application->doRun() /usr/share/php/Composer/Console/Application.php:166
    0.0560    1062696   6. Composer\Console\Application->doRunCommand() /usr/share/php/Symfony/Component/Console/Application.php:189
    0.0560    1062696   7. Composer\Command\RequireCommand->run() /usr/share/php/Symfony/Component/Console/Application.php:841
    0.0564    1065952   8. Composer\Command\RequireCommand->execute() /usr/share/php/Symfony/Component/Console/Command/Command.php:256
    2.1214   96668176   9. Composer\Installer->run() /usr/share/php/Composer/Command/RequireCommand.php:170
    2.1353   96742568  10. Composer\Installer->doInstall() /usr/share/php/Composer/Installer.php:228
   20.8703  396165784  11. Composer\EventDispatcher\EventDispatcher->dispatchPackageEvent() /usr/share/php/Composer/Installer.php:590
   20.8703  396166040  12. Composer\EventDispatcher\EventDispatcher->doDispatch() /usr/share/php/Composer/EventDispatcher/EventDispatcher.php:114
   29.3094  396266864  13. call_user_func:{/usr/share/php/Composer/EventDispatcher/EventDispatcher.php:171}() /usr/share/php/Composer/EventDispatcher/EventDispatcher.php:171
   29.3094  396266864  14. ZF\AssetManager\Plugin_composer_tmp1->onPostPackageInstall() /usr/share/php/Composer/EventDispatcher/EventDispatcher.php:171
   29.3094  396267024  15. ZF\AssetManager\AssetInstaller->__invoke() /usr/share/php/Composer/Plugin/PluginManager.php(178) : eval()'d code:65
   29.3098  396268184  16. include('/home/junior/Munka/Utils/apigility/vendor/doctrine/doctrine-mongo-odm-module/config/module.config.php') /home/junior/Munka/Utils/apigility/vendor/zfcampus/zf-asset-manager/src/AssetInstaller.php:74

```

**Comment by datasage** [comment]
I've run into this as well. While i do have api agility in the project, I'm not entirely sure if its related.

**Comment by adamturcsan** [comment]
I didn't get this issue with only installing into an empty project with `composer require doctrine/doctrine-mongo-odm-module`

**Comment by worthwhileindustries** [comment]
not a fresh install but, ditto

```
root@6ee125cbe6f9:/var/www/html# composer require doctrine/doctrine-mongo-odm-module                                                                                                                                 
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug                                                                                     
Using version ^1.0 for doctrine/doctrine-mongo-odm-module                                                                                                                                                            
./composer.json has been updated                                                                                                                                                                                     
Loading composer repositories with package information                                                                                                                                                               
Updating dependencies (including require-dev)                                                                                                                                                                        
  - Installing doctrine/mongodb (1.6.1)                                                                                                                                                                              
    Loading from cache                                                                                                                                                                                               
                                                                                                                                                                                                                     
  - Installing doctrine/mongodb-odm (1.2.0)                                                                                                                                                                          
    Loading from cache                                                                                                                                                                                               
                                                                                                                                                                                                                     
  - Installing doctrine/doctrine-mongo-odm-module (1.0.0)                                                                                                                                                            
    Loading from cache                                                                                                                                                                                               
                                                                                                                                                                                                                     
                                                                                                                                                                                                                     
Fatal error: Uncaught Error: Class 'Doctrine\Common\Proxy\AbstractProxyFactory' not found in /var/www/html/vendor/doctrine/doctrine-mongo-odm-module/config/module.config.php on line 26                             
                                                                                                                                                                                                                     
Error: Class 'Doctrine\Common\Proxy\AbstractProxyFactory' not found in /var/www/html/vendor/doctrine/doctrine-mongo-odm-module/config/module.config.php on line 26                                                   
                                                                                                                                                                                                                     
Call Stack:                                                                                                                                                                                                          
    0.0003     353648   1. {main}() /usr/local/bin/composer:0                                                                                                                                                        
    0.0047     564576   2. require('phar:///usr/local/bin/composer/bin/composer') /usr/local/bin/composer:24                                                                                                         
    0.0359    1168408   3. Composer\Console\Application->run() phar:///usr/local/bin/composer/bin/composer:43                                                                                                        
    0.0388    1250040   4. Composer\Console\Application->run() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:104                                                                               
    0.0399    1255504   5. Composer\Console\Application->doRun() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:123                                                                           
    0.6534    3649416   6. Composer\Console\Application->doRun() phar:///usr/local/bin/composer/src/Composer/Console/Application.php:231                                                                             
    0.6535    3649416   7. Composer\Console\Application->doRunCommand() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:192                                                                    
    0.6535    3649416   8. Composer\Command\RequireCommand->run() phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:844                                                                          
    0.6539    3652672   9. Composer\Command\RequireCommand->execute() phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:259                                                                  
    2.4120  110325392  10. Composer\Installer->run() phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:175                                                                                      
    2.4275  110331464  11. Composer\Installer->doInstall() phar:///usr/local/bin/composer/src/Composer/Installer.php:216                                                                                             
   22.8480  399121176  12. Composer\EventDispatcher\EventDispatcher->dispatchPackageEvent() phar:///usr/local/bin/composer/src/Composer/Installer.php:563                                                            
   22.8480  399121432  13. Composer\EventDispatcher\EventDispatcher->doDispatch() phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:115                                                
   22.8752  399220128  14. call_user_func:{phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:170}() phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:170
   22.8752  399220128  15. ZF\AssetManager\Plugin_composer_tmp1->onPostPackageInstall() phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:170                                          
   22.8752  399220264  16. ZF\AssetManager\AssetInstaller->__invoke() phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(194) : eval()'d code:65                                                   
   22.8764  399236008  17. include('/var/www/html/vendor/doctrine/doctrine-mongo-odm-module/config/module.config.php') /var/www/html/vendor/zfcampus/zf-asset-manager/src/AssetInstaller.php:74                      
```

**Comment by diegograssato** [comment]
Here has the same problem in the instalations.

**Comment by worthwhileindustries** [comment]
after updating composer from 1.2.0 to 1.5.2 I get a slightly different error.
```
root@6ee125cbe6f9:/var/www/html# composer selfupdate
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Updating to version 1.5.2 (stable channel).
    Downloading: 100%
Use composer self-update --rollback to return to version 1.2.0
root@6ee125cbe6f9:/var/www/html# composer require doctrine/doctrine-mongo-odm-module
Using version ^1.0 for doctrine/doctrine-mongo-odm-module
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing doctrine/doctrine-mongo-odm-module (1.0.0): Loading from cache
Deprecation Notice: The callback Zend\ComponentInstaller\ComponentInstaller_composer_tmp0::onPostPackageInstall declared at phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code accepts a Composer\Script\PackageEvent but post-package-install events use a Composer\Installer\PackageEvent instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:322

Fatal error: Uncaught Error: Class 'Doctrine\Common\Proxy\AbstractProxyFactory' not found in /var/www/html/vendor/doctrine/doctrine-mongo-odm-module/config/module.config.php:26
Stack trace:
#0 /var/www/html/vendor/zfcampus/zf-asset-manager/src/AssetInstaller.php(74): include()
#1 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code(65): ZF\AssetManager\AssetInstaller->__invoke(Object(Composer\Script\PackageEvent))
#2 [internal function]: ZF\AssetManager\Plugin_composer_tmp1->onPostPackageInstall(Object(Composer\Script\PackageEvent))
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Script\PackageEvent))
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(116): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\PackageEvent))
#5 phar:///usr/local/bin/composer/src/Composer/Installer.php(608): Composer\EventDispatcher\EventDispatcher->dispatchPackageEvent('p in /var/www/html/vendor/doctrine/doctrine-mongo-odm-module/config/module.config.php on line 26
```

**Comment by worthwhileindustries** [comment]
see https://github.com/zfcampus/zf-asset-manager/issues/4

**Comment by worthwhileindustries** [comment]
@alcaeus this can be closed now. the below fix resolves it.

https://github.com/zfcampus/zf-asset-manager/issues/4

**Comment by alcaeus** [comment]
Thanks!
